inventory:
  name: '&fDefault Shop'
  slot: 54
shopcurrency:
  type: VAULT # Shop currency support EXP and VAULT
  currency: test01
IRON_INGOT:
  source: IRON_INGOT
  slot: 10
  base_price: 5.0
  current_price: 3.45
  min_price: 2.0
  max_price: 100.0
  supply: 135.0
  demand: 104.0
  price_change_rate: 0.05
  buy_enabled: true
  sell_enabled: true
  real_supply: false
MMOITEM_CUTLASS:
  source: mmoitem:sword:cutlass
  slot: 11
  base_price: 50.0
  current_price: 50.0
  min_price: 25.0
  max_price: 75.0
  supply: 4.0
  demand: 4.0
  price_change_rate: 0.1
  buy_enabled: true
  sell_enabled: true
  real_supply: false
